version: '3.8'
services: 
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@db.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'